---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'default'
  
ErrorPage:
  icon: "app/images/icons/error.png"
UserDefinedForm:
  icon: "app/images/icons/form.png"
KickAssets:
  menu_icon: "app/images/icons/photo.png"
  menu_title: "Files"
StyleGuideController:
  paths: 'themes/default/build/sass/'
  css_files:
    - 'themes/default/css/style.css'
  js_files:
    - 'themes/default/js/script.js'
SVGTemplate:
  base_path: 'themes/default/images/svg/'
  default_extra_classes:
    - 'svg'
